### ISSUE TITLE
eos-sendlog: Options and management tokens for pastebins that support them

### ISSUE THREAD

**Issue by mia-0** [endeavouros-team/eos-bash-shared#4]
Hi, I run 0x0.st.

I frequently receive deletion requests for log files when people realize they contain information they might not want public, and eos-sendlog appears to be one of the tools used to upload them.

While this isn’t bothering me at all so far, I’d still like to suggest adding options to allow users to delete files, set an expiration time, or use longer but hard-to-guess “secret” URLs where supported by the pastebin service. Failing that, default to secret URLs and/or a shorter lifetime (which the user should be notified of).

For 0x0.st and other sites that run the same or similar software, usage instructions for these features are on the homepage. For manual deletion and time limit modification, it uses a token that is returned as part of the HTTP response header when a file is first uploaded. You might want to store this token in the log file along with the returned URL (and hope you’re not breaking anyone’s scripts 😅).

**Comment by manuel-192** [comment]
Thanks for your interesting suggestion!
We will look into it.

All in all, eos-sendlog is a somewhat problematic app because the pastebin services it uses are not always working well, or may cease to exist without notice. That's why the features you are suggesting have not (yet) been in the list of development ideas.
But let's see what we can come up with.

And in case you would be willing to help with the implementation, please let me know! :smile:

**Comment by killajoe** [comment]
I would like to add that we apologize if we caused any inconvenience with the provision in our log tool.

In case you can send users back to us as we are responsible for providing the tool to them without adding teh option to delete thats a valid point you made indeed.

**Comment by dalto8** [comment]
I think the only thing on that list that would be likely to have a material impact on the issue is expiration but that would mostly defeat the point of what we are doing.

I wonder if an option would be to add a warning to eos-sendlog that they are about to post potentially sensitive data and ask them to confirm it.  That way, it might limit how much of that data is posted in the first place.

**Comment by manuel-192** [comment]
@mia-0 
Looks like I misinterpreted your post (unfortunately the first line slipped my eyes...), sorry about that.

We surely must look into the possible alternatives to handling this better. A user warning mentioned by dalto8 is a good idea as well.

**Comment by manuel-192** [comment]
I added eos-sendlog an information window that explains that the data provided by the user is visible to anyone.
My plan is to add a shorter expiration time too, like a week.

The eos-sendlog app is meant for users to send various (typically short) logs about their systems in order for others to see at our forum and eventually help in case something is not working as expected. So I guess a week is usually long enough for the others to read the logs.

I hope this is OK for you Mia. Please let us know what you think.!
