### ISSUE TITLE
Undeclared dependency on sudo (I think)

### ISSUE THREAD

**Issue by Guillaume-Mayer** [endeavouros-team/eos-bash-shared#5]
**pacman -Syu** showed me this warning:
```
(12/15) Check if user should be informed about rebooting after certain system package upgrades.
/usr/share/endeavouros/scripts/eos-script-lib-yad: line 926: sudo: command not found
(13/15) Updating icon theme caches...
```

I use *doas* instead of *sudo*.

Version is eos-bash-shared 24.9-1

**Comment by dalto8** [comment]
The hook should always be running as `root`.  Do we need to elevate permissions in that case?

**Comment by Guillaume-Mayer** [comment]
I always use `doas pacman -Syu` so pacman, at least, runs as root (if it was not clear)

**Comment by manuel-192** [comment]
Thanks for the report!

I changed package eos-bash-shared to version 24.10-1 and it should remove this particular dependency from sudo.

Note that there *may* be other usages of sudo in EOS apps. This is because sudo is installed in EOS by default, and so far you seem to be the first one (that I know of) who has removed sudo in favor of doas.
So if you encounter other similar cases, please let us know (preferably on the EndeavourOS forum, https://forum.endeavouros.com)!

**Comment by Guillaume-Mayer** [comment]
It worked as expecte today , thanks!!

**Comment by manuel-192** [comment]
Thanks for testing and reporting!
